server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo

ly:
  jwt:
    pubKeyPath: F:/TD/ly_rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    appId: wx8397f8696b538317   #公众账号id
    mchId: 1473426802           #商户号
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb #签名生成的秘钥
    connectTimeoutMs: 5000              #连接时长
    readTimeoutMs: 10000      #读取时长
    notifyUrl: http://k7csxn.natappfree.cc/notify/pay #下单通知回调地址